### ISSUE TITLE
Page Not Found 404 when Added to IdneityServer Published IIS

### ISSUE THREAD

**Issue by MagloByte** [ghalebbadran/WinodwsAuthenticationOwinMiddleware#1]
The current version only works on IIS Express.

Solution is impmeneted and it will be pushed in the next update

**Comment by valeriob** [comment]
any chances you could publish those commits ? :D

**Comment by MagloByte** [comment]
I know it took so long to push, i will publish a newer a version during this week, I will notify you immediately.

Thanks.

**Comment by valeriob** [comment]
thanks !

**Comment by valeriob** [comment]
Hi 
Should i remind you to publish the update pls ? :D

**Comment by LinqBeast** [comment]
Thank you very much for this.

Is a fix needed for IIS?  Will definitely need that, if you have it.

Works fine in IIS Express.
